ALTER TABLE product
    ADD COLUMN IF NOT EXISTS proteins_per_unit NUMERIC(10, 2) NOT NULL DEFAULT 0;

ALTER TABLE product
    ADD COLUMN IF NOT EXISTS fats_per_unit NUMERIC(10, 2) NOT NULL DEFAULT 0;

ALTER TABLE product
    ADD COLUMN IF NOT EXISTS carbs_per_unit NUMERIC(10, 2) NOT NULL DEFAULT 0;
