version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_flyway
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipe-service
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    container_name: flyway_migrations
    depends_on:
      - postgres
    environment:
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      FLYWAY_URL: jdbc:postgresql://postgres:5432/recipe-service
      FLYWAY_SCHEMAS: public
      FLYWAY_BASELINE_ON_MIGRATE: true
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./migrations/db.migration:/flyway/sql
    command: migrate

  elasticsearch:
    image: elasticsearch:9.0.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./synonyms:/usr/share/elasticsearch/config/synonyms
      - ./init-index.sh:/usr/local/bin/init-index.sh
    command: [ "/bin/bash", "-c", "elasticsearch-plugin install --batch analysis-morphology && elasticsearch & sleep 20 && /usr/local/bin/init-index.sh && wait" ]

volumes:
  postgres_data:
  elasticsearch_data: